# Generated by Django 4.0.5 on 2022-07-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='registeruser',
            old_name='phone',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='MR', max_length=3),
        ),
    ]
