# Generated by Django 4.0.5 on 2022-07-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceLogin', '0002_rename_name_registeruser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
