# Generated by Django 4.0.5 on 2022-07-15 07:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('AceLogin', '0003_registeruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
