# Generated by Django 4.0.5 on 2022-07-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceLogin', '0004_alter_registeruser_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
