# Generated by Django 4.0.5 on 2022-07-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceLogin', '0005_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
