# Generated by Django 4.0.5 on 2022-07-21 05:41

import AceLogin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceLogin', '0006_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='resume',
            field=models.FileField(blank=True, upload_to='', validators=[AceLogin.validators.validate_file], verbose_name=''),
        ),
    ]
