# Generated by Django 4.0.3 on 2022-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_product_review_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
