# Generated by Django 4.0.3 on 2022-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_product_description_alter_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
